Update pretrained_transformer_tokenizer.py
Traceback (most recent call last):
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/radgraph.py", line 163, in __init__
    self.radgraph = RadGraph(model_type=model_type, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/radgraph.py", line 93, in __init__
    "bert": token_indexers.PretrainedTransformerMismatchedIndexer(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py", line 49, in __init__
    self._matched_indexer = PretrainedTransformerIndexer(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/allennlp/data/token_indexers/pretrained_transformer_indexer.py", line 48, in __init__
    self._allennlp_tokenizer = PretrainedTransformerTokenizer(model_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py", line 79, in __init__
    self.tokenizer = cached_transformers.get_tokenizer(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/radgraph/allennlp/common/cached_transformers.py", line 98, in get_tokenizer
    tokenizer = transformers.AutoTokenizer.from_pretrained(model_name, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 939, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 2213, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 2251, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 2447, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/models/bert/tokenization_bert.py", line 132, in __init__
    super().__init__(
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/tokenization_utils.py", line 435, in __init__
    super().__init__(**kwargs)
  File "/scratch3/nic261/environments/accelerate/lib/python3.12/site-packages/transformers/tokenization_utils_base.py", line 1592, in __init__
    raise AttributeError(f"{key} conflicts with the method {key} in {self.__class__.__name__}")
AttributeError: add_special_tokens conflicts with the method add_special_tokens in BertTokenizer

Attempt to get around this error ^